### ISSUE TITLE
Show audio and video files attached to the trek

### ISSUE THREAD

**Issue by leplatrem** [makinacorpus/Geotrek-rando#131]
- Requires https://github.com/makinacorpus/django-mapentity/issues/34
- [x] Show audio files
- [x] Show video files

**Comment by camillemonchicourt** [comment]
Is it still working in V2 ? 
I know that we can include Soundcloud audios but I dont really want to create an account to host PNE files on Soundcloud.
I have MP3. The best would be to include HTML audio player when we attach an MP3 to an object (TREK, POI, TOURISTIC CONTENT...).
