### ISSUE TITLE
Generalize feedback form to POI too

### ISSUE THREAD

**Issue by leplatrem** [makinacorpus/Geotrek-rando#135]
Currently the feedback form applies to treks.

Since Geotrek-mobile requires a way to submit user-generated content to POIs too, we should generalize this...

**Comment by SBats** [comment]
This is not relevant anymore as Geotrek mobile is not used to contribute content, only to browse.

**Comment by camillemonchicourt** [comment]
This one is on rando but i dont even think that it is relevant to feedback about some POIs, they can complain about POIS through à trek, good to close
