### ISSUE TITLE
Usage filter with icons

### ISSUE THREAD

**Issue by leplatrem** [makinacorpus/Geotrek-rando#222]

**Comment by gutard** [comment]
v2 allows to filter practices with icons in left menu bar

**Comment by camillemonchicourt** [comment]
Yes with ``SPLIT_TREKS_CATEGORIES_BY_PRACTICE`` setting to ``TRUE`` in Geotrek-admin. 
https://github.com/makinacorpus/Geotrek/blob/master/geotrek/settings/base.py#L553
