### ISSUE TITLE
Customize map layers labels

### ISSUE THREAD

**Issue by leplatrem** [makinacorpus/Geotrek-rando#257]
Used to be "Photos satellite", now became "Photos Aériennes"

PNG wants "Images satellitaires" et "Fond de plan" en "Fonds de cartes"

--> Setting !

**Comment by mabhub** [comment]
The layer labels can be customized through custom.settings & translations.

**Comment by camillemonchicourt** [comment]
I remember we talked that we can overlay translations to customize it without editing Geotrek-rando files but didnt saw it in documentation. Is it possible ?
