### ISSUE TITLE
Trek details images

### ISSUE THREAD

**Issue by sylvainbeo** [makinacorpus/Geotrek-rando#271]
If a trek has attached images (one or more), display them in the detail (on the left) with a carousel (if more than one image). It's already done but, POI's images are displayed too ! Do not display POI's images there. POI images should stay in the POI's popup.

**Comment by mabhub** [comment]
Would be done in Admin so the API directly provide array of pictures.

**Comment by camillemonchicourt** [comment]
Great ! Thanks.
