### ISSUE TITLE
Requests with unsupported language should redirect to default language

### ISSUE THREAD

**Issue by gutard** [makinacorpus/Geotrek-rando#283]
Eg. a request to home page with header `Accept-Language: zh-cn` (real case, probably a web search engine) triggers an error log `Could not read '[…]/var/input/zh-cn/api/trek/trek.geojson'` and the page shows no treks.

I think we should set LANGUAGES setting in geotrek rando instead of relying on geotrek admin one.

**Comment by leplatrem** [comment]
I believe that Geotrek-rando should rely on geotrek admin regarding the list of available languages.

But indeed, having a middleware that uses the default language when the incoming requests is done using an unknown language seems like a good idea.

**Comment by mabhub** [comment]
Done by translationService.getDefaultLang
