### ISSUE TITLE
Attach and play sounds and videos

### ISSUE THREAD

**Issue by gutard** [makinacorpus/Geotrek-rando#289]
Related to https://github.com/makinacorpus/Geotrek/issues/1340

**Comment by gutard** [comment]
Attach PDF too.

The "filelist_url" property gives a list of attached files.

**Comment by mabhub** [comment]
Done

**Comment by SBats** [comment]
Done but there's a bug.

To do: 
* check origin policy for media iframes ('X-Frame-Options' to 'SAMEORIGIN) and fix accordingly

**Comment by gutard** [comment]
I think the iframe source should be https://www.youtube.com/embed/xxx instead of https://www.youtube.com/watch?v=xxx

**Comment by camillemonchicourt** [comment]
Yes indeed, this is what YouTube gives as iframe embed code.

**Comment by gutard** [comment]
The problem is on Geotrek-Admin side.
