### ISSUE TITLE
V2 Generic comments about main results page

### ISSUE THREAD

**Issue by Sandrineforge** [makinacorpus/Geotrek-rando#292]
Bonjour, 

Dans un premiers temps quelques retours sur la page principale : 

• Communes :  mettre la liste des communes et pas des massifs
• Vallées :  plutôt l'appeler « Massifs » et mettre la liste des massifs (pas la zone coeur), normalement la zone cœur doit s'afficher sur la carte

• Pictos thématique : Peut-on essayer sans carré autour, juste le dessin qui passe en couleur lorsque l'on clic dessus ? On les voudrait aussi un peut plus petit, mais on va attendre que le responsive soit fonctionnel, car effectivement ils ne sortent pas pareil en fonction de l'écran utilisé.

• Filtres rando, dénivelé, difficulté, durée : mettre des petits marqueurs sur la « barre » pour savoir plus précisément ou est le filtre.

• Picto thématique sur les vignettes sont peut-être un peu trop gros et trop serrés 

• Filtres sur la carte  : peut-être qu'il n'est pas nécessaire de faire apparaître sur la carte les thématiques choisies (puisqu'elles sont en couleur une fois seléctionnées). De même pour les catégories, une fois sélectionnées le "carré" se colorise, pas besoin de retrouver cette info sur la carte. De cette manière, ça réduit un peu le nombre de filtre potentiellement présent sur la carte. À voir...

Sorry for the language, but it's easy in french. If someone wants to translate, no problem. Thanks !

**Comment by camillemonchicourt** [comment]
OK interesting. 
For the filters displayed on the map, I think that it is important to display them all so we see easily all the FILTERS applied at the same place.

**Comment by SBats** [comment]
@camillemonchicourt : 
Si tu ne vois pas d'inconvénients, peut être allons nous dérouler ce sujet en français pour faciliter l'échange ?

@Sandrineforge & @camillemonchicourt : 
Merci pour vos retours ! Ce que j'en pense.

- Pour les communes et les vallées, effectivement ce ne sont pas les champs qui sont chargés, c'est une erreur de ma part. Pour ce qui est des noms, tout est personnalisable via les des fichiers de traduction type .po.
Nous n'avons pas prévu d'afficher la zone coeur sur la carte pour éviter de la surcharger encore plus.

- Pour les pictos des thématiques : Ok je fais l'essai.

- Pour les filtres de type range (difficulté, durée, etc ...), mon objectif a terme est de mettre en place un système avec des points intermédiaires. Je suis actuellement confronté à un problème technique pour le faire, donc j'ai mis en place une version simplifiée pour l'instant. Dans tous les cas je finirai par l'implémenter.

- Les vignettes doivent être retravaillées effectivement (image trop grosse peut être ?).

- Pour ce qui est des filtres présents sur la carte, l'idée principale était que lorsque l'on referme la partie résultat, on puisse avoir un visu sur tous les filtres actifs à un seul endroit. Cela justifie la présence des filtres des thématiques, des vallées, recherche etc...
La présence des filtres des catégories se justifie quand à elle par la possibilité en un clique, au sein de cette liste, d'enlever toute la catégorie d'un coup ainsi que les autres filtres associés. Cela me semblait pertinent d'un point de vue pratique, mais c'est ouvert à débat :).

Globalement je vais essayer d'ouvrir différents sujets pour les éléments d'interface afin de discuter de manière précise des différents aspects.

Pour ce qui est des problématiques techniques, essayez de les créer chacune séparément afin de nous offrir une meilleure vue d'ensemble et une meilleure gestion des problématiques à résoudre.

Je laisse ce sujet ouvert pour qu'il serve aux petites remarques générales sur la nouvelle interface.

Il ne reste plus qu'à avancer ! :+1:

**Comment by camillemonchicourt** [comment]
Voila nos retours sur ces sujets, on en fera des tickets avec l'ensemble des autres retours sur la V2.

**PICTOS DES THEMATIQUES**

Pour les filtres THEMATIQUES, le style nous parait pas mal comme ça pour être cohérent avec les autres filtres au-dessus. La taille ne nous choque pas. Par contre la largeur de ces boutons devra s'adapter en fonction du nombre de thématiques qui sera variable selon les portails. 

En effet les thématiques sont par contre un peu grosses et serrées sur les résultats. Et peut-être seraient-ils mieux en gris. Il faudrait aussi leur ajouter l'info bulle au survol comme on a sur les filtres. 

**FILTRES SUR LA CARTE**

Comme mentionné précédemment et après en avoir discuté en interne, on trouve en effet que c'est bien d'afficher TOUS les filtres sélectionnés sur la carte. Sinon ça va être compliqué pour l'utilisateur de voir rapidement à quoi correspond sa recherche.
C'est assez original comme procédé mais c'est innovant et intéressant. 
Il faudra peut-être un peu plus hiérarchiser les filtres même si les codes aident déjà beaucoup. Différencier ou dissocier les filtres de CATEGORIES, ceux de THEMES et ceux correspondant aux CRITERES D'UNE CATEGORIE ?

**NOM DU FILTRE SECTEUR**

Dans la V1 il était paramétrable dans les SETTINGS du portail - https://github.com/makinacorpus/Geotrek-rando/blob/master/rando/settings/prod.py.sample avec le paramètre SEARCH_PLACEHOLDER car en effet chaque organisme a un nom différent. 

Il me semble mieux de garder cela en paramètre car si c'est géré dans le fichier de traduction, cela sera écrasé à chaque mise à jour de l'appli.

**AFFICHAGE DU COEUR**

Pour l'affichage du COEUR, en effet cela n'est pas prévu par défaut car de toute façon, l'appli ne sait pas dans la BDD quelle type dans la table L_ZONE_REGLEMENTAIRE il devrait utiliser, cela variant selon les UTILISATEURS de GEOTREK et ce ne sont pas tous des parcs nationaux. 

Néanmoins pour se garder la possibilité d'ajouter des zonages en superposition sur la carte, il était possible dans la V1 d'ajouter des couches MBTILES (comme au PNE pour coeur et aire d'adhésion) ou GEOJSON (comme ont fait les PNR PACA pour les limites des 4 parcs). 

Détaillé dans le README - https://github.com/makinacorpus/Geotrek-rando/blob/master/README.rst dans la partie EXTRA BACKGROUND LAYER. Il serait bien de conserver cette possibilité.

**Comment by SBats** [comment]
Merci pour le retour complet @camillemonchicourt !
Alors du coup :
- Le fait de hiérarchiser les filtres sur la carte est une bonne idée. Je pense que c'est une amélioration que l'on pourra peut être amener dans un second temps au vu des autres développement nécessaires, mais j'aime beaucoup l'idée. Je me la garde de coté ;)
- Concernant les traductions customisables, il est probable que l'on passe par 2 fichiers de traduction. 1 contennant les traduction par défaut, et un contenant les traduction custom. Ce dernier ne sera pas publié sur le GitHub et sera créé à l'installation.
- Pour les supperpositions de couches, c'est noté. Ca fera parti des choses à réintégrer.

**Comment by camillemonchicourt** [comment]
OK, pour les traductions, en effet, si c'est pensé comme ça, c'est idéal !
Pouvoir surcoucher la traduction sans toucher aux fichiers internes à l'appli qui évoluent au fil des versions est une très bonne chose.

**Comment by SBats** [comment]
Voilà une nouvelle capture avec quelques changements mineurs (espaces des icones réduits, enlever les bordures inutiles, cards de même hauteur ...)
Golbalement j'ai aléger l'interface là où je pouvais.
![home-v2 3](https://cloud.githubusercontent.com/assets/3982958/6616796/47c908da-c8b2-11e4-8e55-2f1480a0a6f4.png)

**Comment by leplatrem** [comment]
:+1: :heart:

**Comment by Sandrineforge** [comment]
Pour ma part, ça me convient. Nous avons une réunion de travail cette aprèm. Nous pourrons t'en dire plus ensuite.

**Comment by Sandrineforge** [comment]
On aime vraiment bien cette présentation, reste des petits ajustement.

Pour la page d'accueil bloc de gauche : 
• champs Communes : on voudrait un champs d'auto-complétion
• Pas de compteurs sur les champs Massifs et Communes
• mettre un compteur de résultat ( à droite des thèmes, sous les thèmes ?)
• mettre le titre "thème" au dessus des picto thématique, trop d'espace entre les pictos les resserrer à gauche
• Le résultat de la barre de recherche, pas forcémént nécessaire qu'il apparaîsse sur la carte (à voir, le sujet filtre est en réflexion pour le moment)
• Flitre rando avec slider, mettre les marqueurs
• Espace filtre, mettre les titres des catégories en plus gros
•  homogénéiser la taille des vignette de résultat
• favoris sur la photo un peu plus petit (couleur + détourage blanc OK), coeur ou étoile ????
• Picto thématique sur les vignettes : les mettre tous en bas à gauche de la vignette, en gris
•  Vignette événement touristique :  manque date + jours de l'événement
Globalement, manque de contour / délimiation entre les espaces comme pour les champs communes et massifs, avoir des scroll plus fin

**Comment by Sandrineforge** [comment]
Question : What the comportement of the display of the result list ? random ? alphabetical order ? Is it 
customizable ?

Question : quel est le comportement de l'affichage de la liste de résultat ? aléatoire ? ou ordre alaphabétique ? est-ce que c'est quelques choses de paramétrable ?

**Comment by camillemonchicourt** [comment]
- Champs Communes et Massifs : donc vous préfériez un filtre plus comme http://rando.ecrins-parcnational.fr/ ?
- Oui le compteur de résultats est vraiment utile. Sinon en bas de la liste pour ne pas encore alourdir la partie du haut, déjà pas mal chargée ? 
- Résultat de la recherche sur la carte avec les autres filtres. J'aime bien qu'il y ai vraiment tous les filtres regroupés, comme ça pas d’ambiguïté, l'utilisateur voit bien que ce qui est affiché est la somme de plein de filtres. Mais en discussion sur la question AFFICHAGE DES FILTRES SUR LA CARTE. :-)
- Filtres randos. Durée indique bien le rang mais durée et dénivelé n'affichent qu'une valeur alors qu'il s'agit aussi d'un rang.
- Liste des résultats. Non il ne faut pas GRISER les résultats filtrés. Ceux qui ne correspondant pas aux filtres doivent bien être disparaitre. 
La question des résultat GRISES concerne uniquement l'étendue de la carte affichée. Longuement discuté pour la V1 : https://github.com/makinacorpus/Geotrek-rando/issues/202
En effet, il est super intéressant de masquer (ou griser) les résultats qui ne sont pas affichées sur l'étendue de la carte mais c'est pas forcément compréhensible pour tous les utilisateurs. Au final la coche permet d'activer ou non cette fonctionnalité et aussi de l'expliciter. 
On n'a pas eu le temps de le faire sur la V1 mais ça serait idéal sur la V2.
En compromis, on grisait et mettait en bas de la liste les résultats non affichés sur l'étendue de la carte.

**Comment by camillemonchicourt** [comment]
J'oubliais... pour les filtres THEMATIQUES, en effet ça peut être utile d'afficher un titre car c'est pas forcément évident pour un utilisateur de savoir à quoi correspondent ces pictos louches. :-)
Par contre pour leur affichage, les aligner à gauche peut casser la structure de la page. Centré ça fonctionnait bien.

**Comment by Sandrineforge** [comment]
• Pour les champs Communes et Massifs, le système de filtre reste à confirmer, mais ce qui est sûre; si nous avons deux compteurs (résultat + favoris), ça va faire beaucoup de chiffre affiché avec Les compteurs Communes et Massifs.
• Pour la liste des résultats Ok  pour ta remarque, c'est moi qui est pas bien retranscrit 
• Une autre question : la commune notifié sur la vignette ? est-ce bien celle du départ de l'itinéraire ?

**Comment by Sandrineforge** [comment]
On s'interroge également sur les pages statique dans un menu déroulant, est-ce que les utilisateurs vont vraiment aller les consulter ? est-ce que c'est pas plutôt un frein à la consultation ?

**Comment by SBats** [comment]
**Resultats**
- ok pour l'ajout du champ d'auto-complétion
- Ok on enlève les compteurs
- Ok pour le compteur de résultats. A voir où on le place
- Ok pour le titre thèmes. Par contre pour l'alignement des éléments je trouve que l'on conserve une structure plus stable avec les éléments répartis sur la largeur (cela s'adapte selon le nombre d'éléments) plutôt que tout aligné à gauche. Cela évite de donner une impression d'escalier inversé.
- recherche affichée sur la carte : je pense que s'est intéressant d'avoir tout regroupé, notamment si la partie résultats est refermée
- ???  Je n'ai pas compris, mettre quels marqueurs ? La carte ne se mettait pas à jour en fonction des filtres type slider ?
- Bug du non affichage du max sur les sliders corrigé
- Ok pour masquer le champ, on verra comment cela est fait.
- Ok pour la taille des types de fitre
- Taille des vignettes homogénéisée
- Vous m'aviez demandé un favoris type Airbnb d'où le coeur. Coeur ou étoile : choix de l'impression que vous voulez donner.
- Ok pour les pictos de themes.
- Ok pour les type évènement.
- On conserve affiché uniquement les résultats correspondants au trie. C'est le principe du trie de pouvoir alléger l'espace. Le grisé s'applique au filtrage par la carte (éléments actuellements visibles sur la carte)

**Scroll**
- Qu'entendez-vous par scroll plus fin ? S'il s'agit de la largeur des barres de scroll cela dépend de votre navigateur et je n'ai pas la main dessus. (sur le mien par exemple les scroll sont en opacité réduite et par dessus le contenu)

**Organisation des résultats**
- Actuellement c'est par ordre de chargement. Je pense que l'on va aller vers un mode alphabétique. Une contre indication vis à vis de cela ?

**Pages statiques**
- Le problème que l'on rencontre est que dès que l'on possède plus de 4 ou 5 pages statiques (ce qui est quasiment toujours le cas) cela devient difficile de les afficher même sur les grands écrans. C'est donc impossible sur les petits écrans. Je pense qu'il vaut mieux conserver un menu déroulant constant afin d'éviter de surcharger l'interface. Le titre en revanche sera changé pour quelque chose du style 'En savoir plus'.

**Comment by Sandrineforge** [comment]
Resultats
Thèmes : il me semble aussi que c'est graphiquement plus joli comme c'est fait aujourd'hui. Par contre il y a quand même un effet de double entrée thème / catégorie.... je me demande si c'est pas génant à l'utilisation....

Recherche affichée sur la carte : OK, à voir de toute manière quand on aura résolu la question de l'affichage des filtres.

<em>Mettre quels marqueurs ? La carte ne se mettait pas à jour en fonction des filtres type slider ?</em> 
Dans le bloc filtre des randos; il y a trois sliders (difficulté, durée, dénivelé), il me semblait qu'il fallait mettre des petites "marques/barres" de repère sur le slider.... pour voir ou on se situe... À voir, ça semble bien actuellement.
  
Scroll : OK
Organisation des résultats : Je confirme dès que possible

Pages statiques
Possibilité d'avoir un menu déroulant au survol de la souris ? Pour le titre, j'imagine qu'on a la main pour le changer ?

**Comment by Sandrineforge** [comment]
Fenêtre de filtre des catégories : 
• est ce qu'il est possible pour les catégories qui ont q'un seul filtre (type d'usage) d'en masquer le titre, et de faire apparaître directement les choix de filtres ?
• est ce que la longueur de cette même fenêtre peut s'adapter en fonction du nombre de filtre présent ou non ?

**Comment by camillemonchicourt** [comment]
OK pour tout ça.
- Concernant l'ordre des résultats, alphabétique me semble bien. 
- Pour les dernières remarques, je ne comprends pas vraiment l'idée de masquer le titre des filtres qui n'ont qu'un seul filtre. Mieux vaut que toutes les catégories aient un affichage et fonctionnement homogène selon moi. Tant pis si il n'y a qu'un filtre. Il sera en charge à chacun d'utiliser des termes plus approprié que TYPE D'USAGE.
- Idem pour la hauteur, c'est pas mal qu'elles prennent toutes la pleine hauteur pour un affichage homogène.

**Comment by Sandrineforge** [comment]
• pour l'ordre alphabétique de notre côté c'est à voir
• C'est juste quelques retours d'utilisateurs..., je me demandais donc ce qu'il était possible de faire ou  non. En tous cas, quand on ouvre un catégorie autre que rando, ça serait plus facile d'utilisation si les filtres étaient automatiquement dépliés.
• Pour la hauteur, oui ça donne une certaine homogénéité mais tous les retours que j'ai eu c'est que ces gros pavés de couleurs, c'est "moche" et ça prend de la place inutilement. voili

**Comment by camillemonchicourt** [comment]
Concernant l'affichage du cœur, il y a en effet un ticket sur le sujet - https://github.com/makinacorpus/Geotrek-rando/issues/209

**Comment by SBats** [comment]
Thx everyone ! everything is on the issue #297 now !
Please comment on it if you have any feedback.
