### ISSUE TITLE
Thoughts and comments about results display

### ISSUE THREAD

**Issue by SBats** [makinacorpus/Geotrek-rando#293]
For now on we'll stick with french to make exchange easier.

Une réflexion s'impose vis à vis du besoin utilisateur sur les résultats de la page principale.
Le modèle choisi pour la v2 correspond aux cartes créées par Google pour mettre en avant des éléments avec des grands visuels.

La v1 utilisait un système de liste plus classique avec des miniatures et des infos petites et relativement concentrées en terme d'espace.

J'ai un doute concernant l'utilité de gros visuels à cet endroit. Ne serai-ce pas plus pertinent de reprendre un système de liste moins "sexy" mais plus utilisable ?

Merci de vos avis et de vos participations au sujet : @Sandrineforge @amandine-sahl @camillemonchicourt  @leplatrem

**Comment by camillemonchicourt** [comment]
Côté PNE, on aime vraiment bien cette nouvelle présentation qui modernise la présentation et valorise les visuels, inspirée de https://fr.airbnb.ch/s/gap?source=bb.
Tous les gens qui ont regardé ont bien accroché. 
On ne voit pas vraiment en quoi cela est moins utilisable. 

Il faudra par contre que chaque bloc de résultat ait la même hauteur, même quand les titres passent sur 2 lignes.

**Comment by SBats** [comment]
Ok merci pour le retour @camillemonchicourt !
Ce que je craignait, c'est qu'en accordant une trop grande place aux visuels, on prenne le pas sur la carte et l'importance des informations.
Pour l'instant je conserve cette mise en page mais je proposerai peut être d'ici peu une version "liste" des résultats.

**Comment by camillemonchicourt** [comment]
OK

**Comment by Sandrineforge** [comment]
PnC, aussi on aime bien cette présentation ! C'est agréable à utiliser, à regarder... 
Effectivement il faut homogénéiser la taille des blocs. On se demandait aussi si on perdait pas trop de place entre les blocs... à voir quand le responsive sera fonctionnel.

**Comment by SBats** [comment]
Thx everyone ! everything is on the issue #297 now !
Please comment on it if you have any feedback.
