### ISSUE TITLE
"Parc National" label

### ISSUE THREAD

**Issue by gutard** [makinacorpus/Geotrek-rando#294]

**Comment by camillemonchicourt** [comment]
It has to be generic, to be the labelle of a regional park or any other label.

**Comment by camillemonchicourt** [comment]
Quelle est l'idée du PNC derrière cela ? 
@amandine-sahl ?

**Comment by gutard** [comment]
Si j'ai bien compris, il faut faire apparaître le logo de la marque sur la fiche détail sur le portail rando pour certaines catégories de contenus touristiques. Je laisse @amandine-sahl confirmer.

Dans mon idée, c'est une personnalisation du portail rando qui n'entrera pas dans le code générique sur github mais je le mentionne quand même comme issue github pour y penser.

**Comment by camillemonchicourt** [comment]
OK merci pour ces compléments, on va en discuter avec le  PnCEVENNES.

**Comment by Sandrineforge** [comment]
Oui je confirme, on voudrait que le logo de la marque soit présent sur les fiches concernées.

**Comment by camillemonchicourt** [comment]
OK c'est à bien réfléchir donc pour que cette info soit bien utilisée et qu'elle soit le plus générique possible.

**Comment by camillemonchicourt** [comment]
Après discussion PNC et PNE : 

**BDD et ADMIN**
- Il faudrait ajouter un BOOLEEN dans les OBJETS TOURISTIQUES et dans les EVENEMENTS TOURISTIQUES (pour les sorties labellisées)
- Il faudrait un nom générique pour cela. Objet labellisé ? Evénement labellisé ?

**PORTAIL**
- Identifié les objets et evenements marqués avec un picto dans la liste de résultats
- Identifié aussi les objets et événements marqués dans la fiche de l'objet
- Ajouter un filtre global pour n'afficher que l'offre marquée toutes catégories confondues (hebergements, evenements, produits...)

**Comment by mabhub** [comment]
Done
