### ISSUE TITLE
V2 comments on the main map

### ISSUE THREAD

**Issue by Sandrineforge** [makinacorpus/Geotrek-rando#295]
Choses à rajouter, questions... 

À rajouter : 
• bouton recentrer
• POP UP en français
• Bouton + POP UP pour les sources de données externes qui intègre la légende (plan de circulation, maison du Parc)
• Bouton réinitialiser tous (filtres + carto) le fixer sur la carte ?

• On s'interroge sur le changement d'affichage entre le point / ligne en fonction du niveau de zoom, très génant sur les itinéraire traversant : mettre quelques choses au départ (drapeau / marqueur ?)
• La couleur de l'itinéraire est à revoir, le bleu se confond avec la symbolisation des rivières 

• Beaucoup de rando au départ commun, comment gérer l'affichage ?

• Lien marqueur / vignette de résultat, survol de la souris possibilité de les faire inter-réagir ?
• Manque POP UP de la vignette sur la carte (clic vignette résultat = ouverture du marqueur en pop up, ou clic marqueur = ouverture vignette sur la carte)

• Fullscreen pas fonctionnel, manque les infos textuel, affichage de la vignette du marqueur (pour l'instant quand on clic sur la marqueur ça ouvre direct la fiche)
• Carte de situation en bas à droite : le zoom est trop important, pour nous c'est pas pertinent

• Cluster orange: graphisme à revoir : proposition d'un rond orange avec le chiffre en blanc (si vous avez des idées...on est preneur)

**Comment by camillemonchicourt** [comment]
Quelques compléments, remarques : 

- Bouton RECENTRER = Étendue globale
- Affichage point / ligne pour les itinéraires. En effet, le zoom où l'on bascule d'une type d'affichage à  l'autre est à réduire (passer plus tôt sur l'affichage linéaire). Afficher le point de départ. Revoir la couleur des tracés, réduire la transparence et entourer le tracé au survol. Voir http://rando.ecrins-parcnational.fr/
La difficulté principale (qui n'est pas encore apparente sur le portail de test car il y a encore peu de données) est que l'on se retrouve à terme avec 3 ou 4 randos qui partent du même départ et ont des tronçons en communs et qu'il est alors difficile de les dissocier et les sélectionner à partir de la carte. 
- PopUp sur la carte. En effet une popup est intéressante, quand on veut parcourir l'offre sans rentrer directement dans une fiche. Elle permet aussi d'afficher le champ CHAPEAU qui est surtout utile en résumé et première aperçu de l'objet mais n'est pas présent actuellement sur le HOME.
Cependant actuellement un clic sur la vignette ou sur le marqueur envoie directement sur la fiche de l'objet, ce qui garantit que les gens accèdent facilement à la fiche et ne ratent pas celle-ci (problème rencontre sur la V1 où certains utilisateurs n'accédaient pas jusqu'aux fiches...).

**Comment by SBats** [comment]
Thx everyone ! everything is on the issue #297 now !
Please comment on it if you have any feedback.
