### ISSUE TITLE
V2 Details page description and map

### ISSUE THREAD

**Issue by Sandrineforge** [makinacorpus/Geotrek-rando#296]
D'autres points à affiner sur les fiches détails :

• manque le profil altimétrique
• affichage des marqueurs de références dans le texte de descrition (exemple fiche test sentier des grandes tours)

Photo
• Si une seule photo : pas d'affichage en light box ? Manque les légendes sur les photos
• Est-il possible d'avoir ET le diaporama dans le petite espace photo, (quand on clic sur les diapositive) ET la light box lorsqu'on clic sur l'image ?
• mettre des flèches à la place de scroll ou rien si possible
• Quel est l'affichage des médias des POI ?

Espace picto sous photo
• Placement pas idéal, prend trop de place, pas joli : Ces infos synthétique doivent être mises en avant, voir toujours rester sous les yeux
• Picto thématique, pas besoin de mettre le nom, le garder au survol de la souris
• Picto boucle et difficulté ont disparu sur certaines fiches
• Choisir l'intitulé Départ / Arrivée, plutôt que boucle

Bloc réglementation
• Mettre un lien hypertexte sur « réglementation » qui renvoi sur la page en question

Points d'information
• Couleur du bloc = couleur de la catégorie ?
• photo dans la bulle très joli
• Écrire site web + courriel en lien hypertexte
• Si on clic sur le mail : peut-on envoyer directement un mail ?
• Site web : paramétrage pour ouvrir dans un autre onglet
• Diviser le carré bleu / blanc horizontalement, dans la partie bleu la photo en hublot avec les coordonnées, la zone d'écriture est plus large. La partie en blanc « élastique » en fonction de la quantité d'information (ex : 2 points info pour itinéraire de test complet et 1 pour test)
• Lieux d'info interaction avec la carte ?
• Remplacer le picto téléphone (pas joli) par le « i » de information

Carré transport / accès routier
• La forme de bloc, sympa
• Faire des rectangle dans l'autre sens, mettre des carrés empilés, ce qui ne fait pas d'espace vide lorsqu'il n'y a pas de transport sur une fiche, on perd également beaucoup d'espace entre les deux carrés.

Lien web
• Paramétrage pour que ça s'ouvre dans un autre onglet
• Décalage graphique de cette partie par rapport au reste, à voir

**Comment by Sandrineforge** [comment]
Fiche objet touristique
• Bug pour une fiche hébergement, les patrimoines apparaîssent, pour nous ce n'est pas pertinent. (cf la carline)
• Manque le site web
• Manque les info pratiques

Fiche événement touristique
• Manque les info pratiques, intervenant, public visé + accessibilité (attention au terme visible dans la plateforme), nombre de place, réservation

**Comment by camillemonchicourt** [comment]
En effet, les POIs sont des infos attachées aux randos et ne doivent être affichés que sur les randos.

**Comment by Sandrineforge** [comment]
Fiche détail objet touristique, l'icône de téléphone pour le contact... il faudrait trouver autre chose
Le petit liseret de couleur qui rappel la catégorie c'est une bonne idée

**Comment by SBats** [comment]
- j'ajoute le profil altimétrique ce matin
- les marqueurs de référence = les images rouges avec les numéros à l'intérieur ? Si oui je vous propose d'utiliser des listes ordonnées que je styliserai directement en css. C'est plus viable et léger qu'une image.

*Photo*
- Exacte il faut que je prévoie le fait d'afficher la lightbox au click sur la photo centrale.
- je vais mettre des flèches effectivement
- pour les médias des POIs, ce n'est pas encore décidé. Je pensais créer une gallerie (un peu comme les mignatures du visuel de la fiche détail) qui contiendrai les photos, les vidéos et l'audio

*Espace picto sous photo*
- L'une des solutions pourrait être de ne conserver que les icones et de mettre l'information au survol. Cela implique d'avoir un picto pour tous les éléments (d'où l'obligation dans l'admin de mettre un picto au remplissage). Ce serait moins évident de prime abord mais plus structuré.
Autrement auriez-vous une solution à proposer ? La première version qui les contenait dans des cases prenait bien trop d'espace.
- Pour les pictos disparus je vérifie
- Pour l'intitulé de boucle je le remplace

*Bloc réglementation*
Il faut que j'implémente les pages statiques tout d'abord, mais oui effectivement.

*Points d'information*
- Oui pour la couleur
- Merci, il faut que je prévoie une image par défaut si l'image est manquante
- Je remet le style sur les liens oui
- Oui c'est déjà le cas. Le client mail choisi dépend de votre config système
- C'est une problématique récurrente en web. Souvent on préconise de ne pas forcer le comportement utilisateur. Mais comme ici il s'agit d'un lien externe, cela peut se justifier
- J'ai changé l'affichage dans la nouvelle version (visible en ligne). Les infos supplémentaires passent en dessous du carton avec l'image et les infos
- Cela n'est pertinent que si le point d'info est à proximité de l'élément, ce qui est rarement le cas non ? (je veux bien une confirmation sur ce point :) )
- Je pense que je vais remplacer le picto de contact et point d'info par celui d'en savoir plus, et en trouver un autre pour en savoir plus

*Carré transport / accès routier*
- Je ne suis pas sur de comprendre... j'ai privilégié un affichage en 2 colonnes car souvent ces deux infos sont relativement courtes. On peut forcer l'affichage sur une ligne entière s'il n'y a que l'un des deux, mais le fait qu'il y ait un manquant peut rapidement donner l'info à l'utilisateur habitué qu'il n'y a pas de transports en commun. Qu'en pensez-vous ?

*Lien web*
- même problématique qu'au dessus, mais ok.
- Oui effectivement. Mais cela me semble un peu à part comme contenu.

*Fiche objet touristique*
- Je me posais la question de l'intéret des POIS pour un élément type musée par exemple ? Mais sinon ok je l'enlève.
- Je rajoute les infos manquantes

*Fiche évènement touristique*
- Je rajoute les infos manquante

**Comment by Sandrineforge** [comment]
Espace picto sous photo
<em>L'une des solutions pourrait être de ne conserver que les icones et de mettre l'information au survol. Cela implique d'avoir un picto pour tous les éléments (d'où l'obligation dans l'admin de mettre un picto au remplissage). </em> Normalement, sur ce bloc là tous les éléments ont un picto...

<em>Ce serait moins évident de prime abord mais plus structuré. Autrement auriez-vous une solution à proposer ? La première version qui les contenait dans des cases prenait bien trop d'espace.</em>
Pas de solution de notre côté pour le moment...

Points d'information
<em>Cela n'est pertinent que si le point d'info est à proximité de l'élément, ce qui est rarement le cas non ? (je veux bien une confirmation sur ce point :) )</em>
Je laisse @camillemonchicourt répondre :)
 
Carré transport / accès routier
En faites dans l'affichage actuel quand il n'y a pas l'information de transport, il y a un vide à côté du bloc "accès routier", c'est pas très joli visuellement, mais effectivement on sait de suite qu'il n'y a pas de transport. A confirmer donc...

Fiche objet touristique
Non, effectivement il n'y a pas d'interêt à rattacher des POI au musée...

**Comment by camillemonchicourt** [comment]
- Marqueurs de référence - Il s'agit des points de référence. En effet des puces rouges et numérotés que l'on peut positionner sur le tracé de l'itinéraire et auxquelles on peut faire référence dans le DESCRIPTIF PAS A PAS. 
- Pictos infos générales - Pour certaines infos comme la durée, la difficulté... il est vraiment dommage de ne pas afficher la valeur directement et de devoir survoler chaque picto pour avoir l'info. Mais en effet pour les pictos qui se comprennent par elles-mêmes, le picto avec une info au survol suffisent (accessibilité, thématique...). Pas si grave que cela prenne un peu de place selon moi. Le problème est plutôt leur emplacement actuellement
- En effet les lieux d'info sont souvent assez loin de l'objet en question. Souvent à l'entrée de la vallée par exemple. 
- Pour Transport, OK si le bloc passe en pleine largeur quand seulement l'un des deux est renseigné.

**Comment by SBats** [comment]
Thx everyone ! everything is on the issue #297 now !
Please comment on it if you have any feedback.
