### ISSUE TITLE
PREPARE_MAP_IMAP - leaflet-tile-loaded returned empty content

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-rando#298]
PNM is actually on Geotrek-admin 0.32.2. 
MAKE SYNC between their admin and their portal didnt worked these days. 

Make Sync returns an error : 

```
Failed to retrieve http://xx.xxx.xx.xxx/api/trek/trek-91034.pdf (code: 500)
Failed!
```

Indeed, in '/home/admin/Geotrek/var/media/maps' the MAP generation fails each time and '91034.png' is always 0 Ko.

When trying to display the PDF of this trek from Geotrek-admin through IMPR button, it gives an error in browser : 

```
Sorry, there was an error fetching the document. Reason: HTTP Error 500: Internal Server Error
```

So I tried with launching to MAP GENERATION : 

```
bin/django prepare_map_images --url=http://xx.xxx.xx.xxx/
```

It failed on the first path with this error : 

```
AssertionError: Request on http://127.0.0.1:8001/?url=http%3A//xx.xxx.50.163/path/21547/%3Fcontext%3D%257B%2522print%2522%253A%2520true%252C%2520%2522mapsize%2522%253A%2520%257B%2522width%2522%253A%2520800%252C%2520%2522height%2522%253A%2520640.0%257D%257D&selector=.map-panel&waitfor=.leaflet-tile-loaded returned empty content
```

Same error when I try to export PDF of this PATH : 

```
Sorry, there was an error fetching the document. Reason: HTTP Error 500: Internal Server Error
```

While this PATH is normal....

![pnm-path](https://cloud.githubusercontent.com/assets/4418840/6892674/575aab24-d6c6-11e4-9e72-b1b9183d0e49.jpg)

Any idea ?

**Comment by camillemonchicourt** [comment]
Projection error as PNM is not in 2154 ?

**Comment by camillemonchicourt** [comment]
Sorry, it should be in Geotrek-admin...
Wrong tab in my browser. :-)

**Comment by gutard** [comment]
Upgrading to https://github.com/makinacorpus/Geotrek/releases/tag/v0.33.3 should fix or at least improve error logging.

**Comment by camillemonchicourt** [comment]
OK synchronisation is OK now after upgrading to 0.33.4.

Thanks
