### ISSUE TITLE
Categories ordering

### ISSUE THREAD

**Issue by gutard** [makinacorpus/Geotrek-rando#302]
Now, for each type of content (treks, touristic events ou contents), Geotrek-Admin API provides:
- an unique identifier `id`
- an integer `order` that may be `null`

`id` provided by Gootrek-Admin should be used rather than an id hardecoded in Geotrek-Rando. Categories should be ordered using id. All categories with null id should go to the end ordered by name.

**Comment by mabhub** [comment]
Done
