### ISSUE TITLE
V2 - Flèches pour le sens des itinéraires

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-rando#317]
Ajouter le sens des randos avec les flèches sur le tracé comme dans la V1, sinon on ne sait pas dans quel sens se déroule la rando. 

Sur la fiche détail.
Et sur la HOME ?

**Comment by mabhub** [comment]
Done since 5c582c54542a6d5473c282c7a6b7c75995308366

**Comment by camillemonchicourt** [comment]
Thanks, pour changer la couleur des fleches : 

Ajouter les lignes suivantes à la fin du fichier ``_custom-override.scss``

```
.arrow-direction textpath {
    fill: #ffffff;
}
```
