### ISSUE TITLE
V2 - Result list / Add category

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-rando#318]
Plusieurs personnes testeuses n'ont pas bien compris le fonctionnement du nouveau portail avec les CATÉGORIES sur la gauche.

De plus, ils ne comprennent pas tout le temps la distinction entre les THEMES et les CATEGORIES et les THEMES prennent un peu le dessus sur les CATEGORIES.

Une des propositions que nous avions faite, était de mentionner le CATÉGORIE sur chaque objet de la liste de résultat (la couleur ne suffisant pas à notre avis pour facilement associé un résultat à une catégorie).
En plus de faciliter la lecture des résultats, nous pensons aussi que ça répond aux 2 problèmes mentionnés ci-dessus. En effet, ça redonne de l'importance à ces catégories et ça clarifie le lien et l'interaction avec la liste des CATEGORIES à gauche.

Voici un essai : 

![2015-05-home-categories](https://cloud.githubusercontent.com/assets/4418840/7744491/03bdf7bc-ffa4-11e4-94ff-6ef72329e2e2.jpg)

**Comment by mabhub** [comment]
Done since redesign has been merged
