### ISSUE TITLE
V2 - Facebook share doesnt work

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-rando#330]
It opens Facebook but gives an error message.

**Comment by SBats** [comment]
Could you provide some context ? It depends on the conf, so if there's no valid Facebook API key in the settings you will have an error.

**Comment by camillemonchicourt** [comment]
Hum, I made the test again and it worked this time. so it was certainly a temporary FB problem...
I was testing from http://rando.loire-atlantique.fr/

So it worked but just noticed a problem with description : 

![fb](https://cloud.githubusercontent.com/assets/4418840/9362082/e8faa514-469e-11e5-9992-123f9ded9350.jpg)

**Comment by mabhub** [comment]
Mayble should be resolve with something like this : 
http://stackoverflow.com/questions/20533846/single-page-application-with-angularjs-and-facebook-share-button#20537386

**Comment by lellex** [comment]
Maybe due to empty 'ambiance' field (which only few pages have), I inversed the second and third line for facebook share.

**Comment by camillemonchicourt** [comment]
Yes thanks, good to have AMBIANCE after title

**Comment by camillemonchicourt** [comment]
Pour Facebook, il faut créer puis renseigner un APP ID dans les paramètres. 

**MAKINA CORPUS :** Une App ID Facebook n'est pas une simple chaîne, mais l'identifiant numérique d'une App Facebook qu'il faut créer (l'App peut être vide, mais il faut qu'elle existe). L'App Facebook est liée au compte développeur qui la crée. De nombreux sites en décrivent la création, mais celui-ci est assez précis (et récent) : https://support.appmachine.com/hc/en-us/articles/203645706-Create-a-Facebook-App-ID-App-Secret

**MAKINA CORPUS :** Facebook est incapable de crawler une web-app (impossibilité d'exécuter le JS pour récupérer le contenu).
C'est pour cela que nous avons créer cette fonctionnalité de partage custom, nécessitant un App ID.

Voici les étapes effectuées :
- Aller sur https://developers.facebook.com/
- Afficher le menu du profil développeur et cliquer sur ajouter une app
- Sélectionner site web
- Rentrer le nom de l'app souhaitée et cliquer sur "Créer un nouveau App ID"
- Ignorer le curseur pour le mode test
- Sélectionner la catégorie (pour mon test: sport) et cliquer sur "Créer un Id d'App"
- Scroller jusqu'au premier champ concernant l'url du site et y renseigner l'URL du site
- Dans le bloc "Etapes suivantes" cliquer sur "Aller directement board de développement" dans le texte. Cela devrait ouvrir un nouvel onglet
- Remplir le champ "Domaine" avec la même url que précédemment et renseigner un email de contact
- Cliquer sur le lien "Statu" dans le menu de gauche
- Cliquer sur le bouton en haut de page pour passer l'application en production

Après toutes ces étapes copier l'App ID et le coller dans la config geotrek-rando (https://github.com/makinacorpus/Geotrek-rando/blob/master/SETTINGS.md#social-networks). Une fois les fichiers regénérés via la tache npm, le partage Facebook devrait fonctionner.

**Comment by camillemonchicourt** [comment]
Quelques infos complémentaires (Makina Corpus) : 
Facebook exige un véritable nom de domaine (App Domains), le partage Facebook ne peut donc pas fonctionner si Geotrek-rando est installé sur une IP mais n'a pas encore de domaine. 

Par ailleurs, dans la conf de Geotrek-rando, il faut mettre le domaine complet dans le paramètre ``API_URL``. ``URL/data`` par exemple et pas seulement ``/data``

**Comment by camillemonchicourt** [comment]
This method was not working anymore and has been replaced in Geotrek-rando 2.18.0 by share method : https://github.com/GeotrekCE/Geotrek-rando/releases/tag/2.18.0
