### ISSUE TITLE
V2 - Highlight trek lines on HOME

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-rando#335]
A partir d'un certain niveau de zoom, sur la page d'accueil, les tracés des randos sont affichées en plus des points de départ. 
Il faudrait alors que lorsque l'on survole un point de départ, le tracé correspondant soit mis en surbrillance comme c'était le cas sur la V1.

**Comment by SBats** [comment]
It's already working like this. Any idea of a non working example ?

**Comment by camillemonchicourt** [comment]
Exact, my mistake. I close it.
