### ISSUE TITLE
Touristic content URL

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-rando#336]
URL should use the category name and not the generic and technical name TOURISTIC_CONTENT.

Example : 

[GEOTREK_RANDO_URL]/contenu-touristique/parapente-aire-de-decollage/

should be 

[GEOTREK_RANDO_URL]/pleine-nature/parapente-aire-de-decollage/

**Comment by gutard** [comment]
Actually the problems seems to be in admin. I opened https://github.com/makinacorpus/Geotrek/issues/1495 to track that.

@SBats, if I fix category slug property in admin, are you sure it will not break Geotrek-rando ?

**Comment by SBats** [comment]
I don't see any reason for it not to work. We'll check it on a pre-prod maybe ?

**Comment by gutard** [comment]
The problem is on Geotrek-Admin side. I close here.
