### ISSUE TITLE
Link to a random element of a category on home page

### ISSUE THREAD

**Issue by gutard** [makinacorpus/Geotrek-rando#338]

**Comment by camillemonchicourt** [comment]
It was available in V1 : https://github.com/makinacorpus/Geotrek-rando/tree/v1.X#home-popup

**Comment by camillemonchicourt** [comment]
Je ne sais pas si c'est car l'info n'est simplement pas affichée ou si c'est car elle n'est pas récupérée, mais il faudrait pouvoir afficher le picto de la catégorie de l'objet (+ nom catégorie au survol du picto) et que l'objet soit clicable pour accéder à sa fiche détail.

Merci.
