### ISSUE TITLE
[PNE] Integrate news feed on home page

### ISSUE THREAD

**Issue by gutard** [makinacorpus/Geotrek-rando#339]

**Comment by gutard** [comment]
@camillemonchicourt, peux-tu nous donner (si besoin par mail) l'url du flux en question stp ?

**Comment by camillemonchicourt** [comment]
OK, on doit avancer sur ce point en même temps que sur le maquettage de la HOME. 
Je vous transmets un exemple de flux dès que possible si on garde cette idée de flux ACTUS sur la HOME.

**Comment by gutard** [comment]
@camillemonchicourt, @SBats, est-ce fait ? ou plus d'actualité ?

**Comment by camillemonchicourt** [comment]
C'est d'actualité mais pas fait.
Le flux n'est pas encore en place mais la commande est passée et il sera fait d'ici la fin décembre.

**Comment by SBats** [comment]
We'll wait for the feed to be ready and fully functionnal before developping anything.

**Comment by camillemonchicourt** [comment]
Yes of course. The feed will be json, i guess this is The best format to use.

**Comment by SBats** [comment]
Indeed

**Comment by camillemonchicourt** [comment]
Here is the json feed ! 

http://www.ecrins-parcnational.fr/api/views/flux_actus.json

Including 50 latest PNE news with :

- Vignette de menu : lien vers l'image de base
- Titre : titre du l'actu
- Chapeau : Résumé de l'actu
- Date de publication : timestamp
- Id (Nid) 
- Lien : lien vers le contenu sur le site

**Comment by SBats** [comment]
Done but linked to GTE customisation

**Comment by camillemonchicourt** [comment]
As Geotrek-rando parse and display the feed in javascript, we had to allow cross-domain access to the feed to our Geotrek-rando URL. 

On our website that generates the NEWS feed :
```
    <IfModule mod_headers.c>
      Header add Access-Control-Allow-Origin: "http://www.URL_GEOTREK_RANDO"
    </IfModule>
```
Another way would have been to parse it on Geotrek-rando server side but there is no Python nor PHP on Geotrek-rando that is full HTML and javascript. 
```
    <?php echo file_get_content("http://www.ecrins-parcnational.fr/api/views/flux_actus.json");
```
