### ISSUE TITLE
Reservation widget for FFCAM

### ISSUE THREAD

**Issue by gutard** [makinacorpus/Geotrek-rando#340]
Depends on https://github.com/makinacorpus/Geotrek/issues/1478

**Comment by gutard** [comment]
Code example:
```javascript
<script src="http://centrale.ffcam.fr/js/widget.js" type="text/javascript">
</script><script type="text/javascript">
//<![CDATA[
jQuery(window).load(function(){
BK_widget.init({target:'booking', structure:'47ntr9jg1dif', lang:'FR'});
});
//]]>
</script>
```

**Comment by SBats** [comment]
Their widget.js file use old jQuery plugins so we have to include jQuery migrate...

**Comment by camillemonchicourt** [comment]
Hum, bad point if it is complicated and loud.
We can ask them if they have (or plan) to update their widget.
I will call them today.

**Comment by SBats** [comment]
It's not complicated but it add weight. It could be a good idea to ask them for a possible  udate indeed !

For the moment I've created the widget in customisation files. It's working but not connected to the data send by Geotrek Admin yet.

**Comment by camillemonchicourt** [comment]
OK, which JQUERY plugin/version should I ask them to use in order to dont say mistakes ? :-)

**Comment by gutard** [comment]
@SBats, I deployed on prod-geotrek-fr and created a touristic content "Refuge FFCAM"

**Comment by SBats** [comment]
@camillemonchicourt the most recent possible. But it mostly depends of which browsers they want to support. Legacy's mean 1.X.X and modern is 2.X.X (currently 1.11.3 and 2.1.4)
The point is mostly they should not rely on libraries or plugins that are old or deprecated.

@gutard Thanks ! I'll try this.

**Comment by SBats** [comment]
@gutard It works ! We'll wait to see if @camillemonchicourt have any informations from the dev. Otherwise it's ready.

**Comment by camillemonchicourt** [comment]
I talked with them, they will check that and let us know.

**Comment by SBats** [comment]
Nice ! Thx for contacting them !

**Comment by camillemonchicourt** [comment]
A jQuery update is scheduled. No date yet.
