### ISSUE TITLE
Zoom when new filter reduce result set

### ISSUE THREAD

**Issue by gutard** [makinacorpus/Geotrek-rando#344]
Or document the option if it already exists

**Comment by camillemonchicourt** [comment]
It seems to be already available and documented in the great file `SETTINGS.md` file (https://github.com/makinacorpus/Geotrek-rando/blob/master/SETTINGS.md).

> UPDATE_MAP_ON_FILTER - Boolean - false - If true, update map viewport each time a filter is changed.

Available here - https://github.com/makinacorpus/Geotrek-rando/blob/master/src/app/config/settings.default.json#L68

Just to make sure that it works when we link to the portal with a selection. Example : http://myrandowebsite.com/?categories=T1&cities=44004&cities=44005

**Comment by SBats** [comment]
The fact that the map bounds and center on the first load is independant from that option and is always active no matter the option value.

**Comment by camillemonchicourt** [comment]
OK perfect.
