### ISSUE TITLE
V1 to V2 - URL rewriting ?

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-rando#347]
Example - http://rando.ecrins-parcnational.fr/fr/boucle-du-pigeonnier-dans-le-cirque-du-gioberney would become http://rando.ecrins-parcnational.fr/itineraire/boucle-du-pigeonnier-dans-le-cirque-du-gioberney ?

**Comment by SBats** [comment]
Yes

**Comment by camillemonchicourt** [comment]
Not sure if I was clear. 
I was asking if there is some URL rewriting included in V2 to dont loose external links to V1 treks ?

**Comment by camillemonchicourt** [comment]
The rewriting rules are already included ?

**Comment by camillemonchicourt** [comment]
Done in documentation - https://github.com/makinacorpus/Geotrek-rando/blob/master/docs/http-server.md#redirect-urls-from-v1
