### ISSUE TITLE
Trek detail - Language change should change URL ?

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-rando#348]
When I am on a trek in French and change the language, URL dont change. 

Example : http://rando.mercantour.eu/itineraire/la-cime-de-colmiane/
But when I go on this trek from the HOME in EN, the URL is not the same. http://rando.mercantour.eu/trek/la-cime-de-colmiane/

So the same content has 2 URLs ?

**Comment by SBats** [comment]
A content has a an Unique URL for each language. the end of the URL (here: la-cime-de-colmiane) depends on the title in the admin. For mercantour it's the same end url because they didn't translate the title for the english version

**Comment by camillemonchicourt** [comment]
OK... I understand that it is due to their context...
But it seems like there is still something that don't change. 
When I am on a trek and that I switch from one language to another, the URL don't change. 
Maybe it is good like this but just wondering if it cant bring problems such as duplicate content. 

I'll do deeper tests on our V2 later.

**Comment by mabhub** [comment]
Each localised version of a content have its own localised URL.
But when switching language, the __current browser location does not update__.

Need to fix.
