### ISSUE TITLE
BASEMAP - Switch automatically depending on extent

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-rando#355]
Similar problem to https://github.com/makinacorpus/Geotrek/issues/1527
But this time on a public applicatino that shouldnt become a WEBSIG. 
The problem is that when we are on PNAM (IT) IGN basemap is not good. 
An idea would be to switch automatically from IGN to another one (OSM ? ESRI ? Other ?) depending on where we are zooming...

I think we talked about other ideas in the past but cant remember which...

**Comment by mabhub** [comment]
Doable since 14c917edfabe475cfbf28719ef06073b339d4b69 by adding a polygon defining the limit of each layer.

This kind of setup of a layer will contition its display to the polygon :

        {
            "LAYER_URL": "http://...tile layer server...",
            "BOUNDS": "polygon_data.geojson",
            "OPTIONS": {
                "minZoom": 1,
                "maxZoom": 17
            }
        }
