### ISSUE TITLE
V2 mobile responsive - 3D

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-rando#358]
It can't be used.

![screenshot_2015-11-10-05-16-09](https://cloud.githubusercontent.com/assets/4418840/11055128/0d98d11e-8774-11e5-9572-b0c8de62f16c.png)

**Comment by SBats** [comment]
I don't thinkg it's a good idea to allow this feature on mobile. And in fact this issue is depending on [this repo](https://github.com/makinacorpus/rando3D), not geotrek rando.

**Comment by camillemonchicourt** [comment]
Yes i also agree that it would be better to hide 3D on responsive mobile version as it will not work well on it.
Just not sure on tablet but maybe easier to do the same on mobile and tablet ?

**Comment by SBats** [comment]
In fact there's not only a display issue but a performance one for mobile devices, so we need to hide the 3D button on phone AND tablets.

**Comment by camillemonchicourt** [comment]
OK best choice indeed
