### ISSUE TITLE
V2 share detail page

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-rando#360]
Tested on mobile. 
Email just open an empty email
Twitter only display trek title
Facebook displays : 
![screenshot_2015-11-10-05-15-38](https://cloud.githubusercontent.com/assets/4418840/11055164/7cc3f79e-8774-11e5-9dd6-425601db6f81.png)

**Comment by mabhub** [comment]
These cases are from the built-in share function of the phone, or from the share buttons of Geotrek ?

**Comment by camillemonchicourt** [comment]
It does the same with both. 
It happens on homepage but also from an object detail page.

**Comment by SBats** [comment]
* Facebook: Not able to crawl single page apps content, is linked to https://github.com/makinacorpus/Geotrek-rando/issues/303.
* Mails: There's seems to be an issue as the subject and content fiedls are filled  but ignored by the mail client
* Twitter: the limited number of caracters force us to have a small text. So we only put the title in it;

**Comment by camillemonchicourt** [comment]
OK thanks for investigations. 
For Twitter sharing the title of a page without including link dont really make sense.
I remember that title + links worked in V1 as small text but if not possible it would be better to share link rather than title.

**Comment by SBats** [comment]
My bad, the link is also used for twitter.

**Comment by camillemonchicourt** [comment]
Oh yes, now it is in my tests. Thanks.
