### ISSUE TITLE
V2 - meta description

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-rando#363]
It seems like there is a missing tag in Geotrek-rando V2 metadata. 
As when searching Rando Mercantour on Google here is the result : 

```
Parc National du Mercantour - Parco delle Alpi Marittime
rando.mercantour.eu/
root.metaDescription}}
‎À savoir - ‎Faune - ‎Les Parcs - ‎Marittime Mercantour Trekking
```

Or maybe they forgot to fullfil a setting ?

Same as https://github.com/makinacorpus/Geotrek-rando/issues/360 ?

**Comment by mabhub** [comment]
It seems that this happens only for home page / results page : https://encrypted.google.com/search?q=site:rando.mercantour.eu

**Comment by camillemonchicourt** [comment]
I am wondering if search engines index the homepage (landpage) or the search/result page as they have the same URL ?
For the landpage I guess we can just include title and description in <meta> section. 
But for the search/result page, shouldnt we add a setting for title and description (in each language) as in V1 ? Or there is a better way to do ?

**Comment by camillemonchicourt** [comment]
After checking search/result page source code of http://rando.loire-atlantique.fr/ it gives : 

``` HTML
<!DOCTYPE html>
<html lang="fr" ng-app="geotrekRando">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title ng-bind="$root.metaTitle"></title>
  <meta name="description" content="{{$root.metaDescription}}">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <base href="/">
  <meta ng-repeat="tag in $root.twitterTags" name="{{tag.name}}" content="{{tag.content}}">
  <meta ng-repeat="tag in $root.facebookTags" property="{{tag.property}}" content="{{tag.content}}">
  <link rel="icon" type="image/png" href="{{$root.favIcon.png}}" />
  <!--[if IE]><link rel="shortcut icon" type="image/x-icon" href="{{$root.favIcon.ico}}" /><![endif]-->
  <link rel="stylesheet" href="rando-vendors.css">
  <link rel="stylesheet" href="rando.css">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <!--[if IE 9]>
    <script type="text/javascript" src="app/vendors/scripts/xhr-xdr-adapter.js"></script>
    <link rel="stylesheet" type="text/css" href="ie9-compatibility.css">
  <![endif]-->
  <script src="rando-vendors.js"></script>
  <script src="rando.js"></script>
  <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
</head>
<body>
  <div ui-view class="main-container"></div>
</body>
<script> 
  var $buoop = {
    c:2,
    vs: {i:9,f:30,o:27,s:7},
    reminder: 0,
    reminderClosed: 1,
    test: false,
    text_fr: "Votre navigateur ne permet pas l'affichage du site dans des conditions optimales. Dans un objectif de <b>performance</b>, de <b>sécurité</b> et de <b>qualité de visite</b>, <a>nous vous recommandons de mettre à jour votre navigateur</a>",
  }; 
  function $buo_f(){
    var e = document.createElement("script");
    e.src = "//browser-update.org/update.min.js";
    document.body.appendChild(e);
  }
  try {document.addEventListener("DOMContentLoaded", $buo_f,false)}
  catch(e){window.attachEvent("onload", $buo_f)}
</script>
</html>
```

**Comment by mabhub** [comment]
That's not a HTML source problem. It's only about angular context for home & results list and the way it update variables. There's nothing to investigate about HTML source or contents.

_(Also, homepage and results list does not have same url because of query strings)_

**Comment by camillemonchicourt** [comment]
OK thanks for the answer.

**Comment by SBats** [comment]
This issue doesn't exist for https://encrypted.google.com/search?hl=fr&q=rando%20loire%20atlantique

The thing is :
* Homepage use the metaDescription which is a string in the translation files.
* Flat pages use their name.
* Detail page use the description teaser.

In the case of Mercantour, maybe they could use google webmaster tools to force updating google results, as the metaDescription traduction is present in their files.

I close this issue for now, if the issue come back please re open it.

**Comment by camillemonchicourt** [comment]
OK thanks.
