### ISSUE TITLE
Search engine index and language

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-rando#370]
With searching [`site:rando.mercantour.eu`](https://www.google.fr/#q=site:rando.mercantour.eu) on [google.fr](https://www.google.fr/) I saw that they indexed the pages with EN url : 

> Saorge
> rando.mercantour.eu/trek/saorge/
> Après avoir flâné d'églises en couvent dans le dédale des ruelles obscures d'un bastion qui surveille depuis toujours la route de la Roya, cette balade familiale ...

Maybe because they have the same content in French and English as they published all treks in EN without translating ?

Or something else ?
In V1, there was a command to ping the sitemap to Google. Is there still something similar in V2 ?

**Comment by mabhub** [comment]
Try browsing the site in english: EN translation arn't done.
