### ISSUE TITLE
Clarify and homogenize duration display in hours and days

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-rando#437]
See https://github.com/makinacorpus/Geotrek-mobile/issues/173

**Comment by gutard** [comment]
If Geotrek-Rando uses the the @duration_pretty@ attribute it should be ok. We should check this is the case.

**Comment by camillemonchicourt** [comment]
Yes, fixed in Geotrek-admin 2.7.1 - https://github.com/makinacorpus/Geotrek/issues/1563
