### ISSUE TITLE
RESPONSIVE - Menu display

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-rando#474]
Tests on NEXUS 7 (1920-1200)

When clicking on FAVORITES, the rest of the menu is displayed over.
Also the 3 first favorites have grey background, while the others have white background. 

![20160115_111649](https://cloud.githubusercontent.com/assets/4418840/12351058/4b3da90a-bb7b-11e5-8b85-2ca3599184fa.jpg)

**Comment by camillemonchicourt** [comment]
Aussi l'ordre des ITEMS n'est pas très pertinent. Les outils sont avant le contenu.
Ça devrait être 
- LE PARC 
- FAVORIS
- LANGUES
- PARTAGE

**Comment by mabhub** [comment]
The bug was fixed.
For changing the order of the elements please create a new enhancement issue.

**Comment by camillemonchicourt** [comment]
OK thanks !
