### ISSUE TITLE
SAFARI - No data displayed

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-rando#478]
![safari-pnc](https://cloud.githubusercontent.com/assets/4418840/12354701/eb9ae054-bb97-11e5-9cf8-51f5676f9c74.jpg)

**Comment by SBats** [comment]
We won't provide support for Windows Safari version. Apple officially stoped supporting it in 2012 (https://en.wikipedia.org/wiki/Safari_(web_browser))

**Comment by camillemonchicourt** [comment]
OK didnt knew ! 
It is a very old version then, I understand.
Thanks.
