### ISSUE TITLE
INTERNET EXPLORER - CSS

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-rando#481]
Problem with title and button to collapse panel. 
Same problem to collapse panel on recent SAFARI. 

![ie-search](https://cloud.githubusercontent.com/assets/4418840/12356054/d34348a8-bba0-11e5-9396-f2e7c10ee995.jpg)

**Comment by SBats** [comment]
Please provide more context for these issues.
Which version of IE, of Windows.
Which version of Safari, of OSX.

**Comment by camillemonchicourt** [comment]
The screenshot is with IE10 but it seems like the Menu problem also happens in IE11.
About Safari, it was on MAC with version 9.X

**Comment by camillemonchicourt** [comment]
tested, it is OK. thanks
