### ISSUE TITLE
Style for language displayed

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-rando#502]
In V2, actually we don't see in which language we browse the website. 
Maybe just put in bold FR or UK, dependng on the language we use, could clarify that.

**Comment by mabhub** [comment]
By default language selector is displayed like a `<select>` option box so the active language is obvious.

Always displaying all available languages may be a specific behavior of your header template.
In your case, highlighting the active language could easily be done with customization CSS files.

**Comment by camillemonchicourt** [comment]
OK, thanks
