### ISSUE TITLE
How search engines see Geotrek-rando V2 portals

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-rando#505]
Maybe I don't know how it works and don't really know AngularJS but I don't understand something. 
When I display the source code of a Geotrek-rando V2 portal, it dont display any title, nor description, nor content. It displays the message - "Votre navigateur ne permet pas l'affichage du site dans des conditions optimales. Dans un objectif de <b>performance</b>, de <b>sécurité</b> et de <b>qualité de visite</b>, <a>nous vous recommandons de mettre à jour votre navigateur</a>".

Maybe this is not what search engine see ?

But when I check with a tool like https://varvy.com/tools/, it says the same. 

Maybe I missed something. May could be interested to browse one portal with Google Webmasters Tools but it needs to include verification code inside code.

**Comment by SBats** [comment]
Rando v2 is a Single page app based on Angular 1. This mean that most of its content (almost all) is loaded and bootstraped via javascript execution.
In fact most of the web crawlers can't execute js web app and display only the basic markup (which notably contains the text you describe).

Google, on the other hand, is able to crawl js web app, and notably AngularJS pages (framework which belongs to Google). It execute the website and read it as we, human with modern browser, see it.

**Comment by camillemonchicourt** [comment]
OK thanks a lot for the precisions !

**Comment by camillemonchicourt** [comment]
Pour que Google indexe les différentes pages d'un portail et pas uniquement la HOME : 

**QUESTION :**
Lorsque l'on cherche sur google "site:http://destination.cevennes-parcnational.fr/" on n'obtient qu'un résultat qui correspond à la page d'accueil.

**REPONSE :**
Il faut activer le mode HTML5 d'angular en ajoutant dans src/app/config/settings.custom.json :

    "ENABLE_HTML_MODE": true,

Cela fera disparaître le # des URLs qui fait que tout le site est vu par Google comme une page unique.

Par exemple, le site du parc des grands causses est en mode HTML5 et est correctement indexé par Google : https://www.google.fr/search?q=site%3Arando.parc-grands-causses.fr

Idem pour L'exemple du tour du lac de Serre-Ponçon est plus parlant: https://www.google.fr/search?q=site:itinerance.alpesrando.net

Note: le mode HTML5 nécessite que le serveur web soit configuré pour rediriger les requêtes vers index.html lorsqu'elles ne correspondent pas à un fichier. Par exemple avec nginx:
```
location / {
  try_files $uri $uri/ /index.html;
}
```
