### ISSUE TITLE
RESPONSIVE - Add scroll to category menu

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-rando#509]
When there is a lot of categories, we cant see the whole menu.
Maybe a scroll inside the menu in case it is cut could solve that.

![screenshot_2016-01-21-16-53-33](https://cloud.githubusercontent.com/assets/4418840/12485984/db74dc7a-c060-11e5-830c-e56a7d720cc6.png)

![screenshot_2016-01-21-16-53-48](https://cloud.githubusercontent.com/assets/4418840/12485990/deeecb0e-c060-11e5-8b9c-40c1e9744e4a.png)

**Comment by mabhub** [comment]
Fixed by efaa73eb57fcd6d1403824ff385679824d1e6baa
