### ISSUE TITLE
2.14 CSS problem ? Image lightbox display

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-rando#579]
Tested on Chrome on 2.14.2 on this page - http://mtcv.ecrins-parcnational.com/a-pied/le-saut-du-laire/
With nothing special in ``_customisation.scss``.

When clicking on an image on a detail (trek image or POI image), the lightbox dont open and the page is refreshed with a display problem : 

![popup-01](https://cloud.githubusercontent.com/assets/4418840/15893788/4065b328-2d82-11e6-9444-2935b9e1a341.jpg)

When clicking on BACK TO MAP, the Search Map also has a display problem : 

![popup-image02](https://cloud.githubusercontent.com/assets/4418840/15893795/51ff7a38-2d82-11e6-9047-e2eb417cd655.jpg)

**Comment by mabhub** [comment]
I can't test it myself right now, but could you please try remplacing occurences _(2 if I'm right)_ of
```
templateUrl: '/app/gallery/templates/lightbox-gallery.html',
```
by 
```
template: require('./templates/lightbox-gallery.html'),
```
and rebuild everything ?

**Comment by camillemonchicourt** [comment]
OK I understood. Thanks a lot. 

I tried to replace by ``template: require('./templates/lightbox-gallery.html'),``

there https://github.com/makinacorpus/Geotrek-rando/blob/master/src/app/pois/controllers.js#L41 and there https://github.com/makinacorpus/Geotrek-rando/blob/master/src/app/detail/controllers.js#L55

But ``npm run dist`` returned this error : 

```
[21:26:17] Browserify Error { [Error: Cannot find module '/app/gallery/templates/lightbox-gallery.html' from '/home/myuser/Geotrek-rando/src/app/detail']
```

So I replaced it by ``template: require('../gallery/templates/lightbox-gallery.html'),``, ran ``npm run dist`` again and it is working now ! 

Thanks for the solution. 

PS : I was thinking about doing a PR with the changes but not sure my changes are the nice ones.

**Comment by mabhub** [comment]
It's cool that you have found a way to adjust the template path :)

Don't hesitate to do the Pull-Request ! As soon as you submit it, we will review it before merging anyway.

**Comment by camillemonchicourt** [comment]
OK thanks. 
I didnt really did it the right way as I dont have a local clone of the git deposit so I made it directly in Github, which make 1 commit by file changed. :-/
But it makes only 1 PR - https://github.com/makinacorpus/Geotrek-rando/pull/587

Also wondering there is also a path problem with media-modal here - https://github.com/makinacorpus/Geotrek-rando/blob/master/src/app/pois/controllers.js#L99
But I have no example to test it. I will try to get one example to test it.
