### ISSUE TITLE
Add a VERSION file

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-rando#580]
It is very useful in Geotrek-rando V1 and in Geotrek-admin to know which version is actually installed in the server.

**Comment by gutard** [comment]
In source code, the current version can be found in packages.json file, or in CHANGES.md file.
Since 2.9.0 release, you can get CHANGES.md file over HTTP (eg. http://grand-tour-ecrins.fr/CHANGES.md).

**Comment by camillemonchicourt** [comment]
OK I see, perfect, thanks !
